repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: detect-aws-credentials
    args: [--allow-missing-credentials]
  - id: detect-private-key
  - id: check-added-large-files
    args: [--maxkb=4000]
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-case-conflict
  - id: check-merge-conflict
- repo: git@github.com:exdial/pre-commit-hooks
  rev: 363a879a45d49886b1d229a075af8ba6b23bfc86
  hooks:
  - id: terraform-validate
  - id: terraform-fmt
  - id: terragrunt-hclfmt
